# Generated by Django 4.2.7 on 2023-11-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userinput", models.CharField(max_length=30)),
                ("myanswer", models.CharField(max_length=30)),
            ],
        ),
    ]
