# Generated by Django 4.2.7 on 2023-11-18 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="myanswer",
            new_name="mycalvalue",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="userinput",
            new_name="userinputvalue",
        ),
    ]
